"""test

Revision ID: 44140f691e1a
Revises: None
Create Date: 2013-09-12 17:37:25.108782

"""

# revision identifiers, used by Alembic.
revision = '44140f691e1a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
